#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/remirousselet/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/remirousselet/dev/rrousselGit/riverpod/packages/flutter_riverpod/example"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/remirousselet/dev/rrousselGit/riverpod/packages/flutter_riverpod/example/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_CLI_BUILD_MODE=debug"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzMuMC0xLjAucHJlLjMwMw==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXI=,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049MGE2ZTRhNmRlNg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MGE2ZTRhNmRlNg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTE3Mi4wLmRldik="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/remirousselet/dev/rrousselGit/riverpod/.dart_tool/package_config.json"
