targets:
  $default:
    builders:
      lint_visitor_generator:
        enabled: true
        generate_for:
          include:
            - "**/*.dart"
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  lint_visitor_generator:
    import: "package:lint_visitor_generator/builder.dart"
    builder_factories: ["lintVisitorGenerator"]
    build_extensions: { ".dart": [".lint_visitor_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]