name: lint_visitor_generator
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  analyzer: ^7.0.0
  build: ^3.0.0
  build_config: ^1.1.0
  collection: ^1.17.1
  meta: ^1.15.0
  path: ^1.9.0
  source_gen: ^3.0.0
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^3.2.1
  source_gen_test: ^1.0.4
