name: lint_visitor_generator
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.17.1
  meta: ^1.7.0
  path: ^1.9.0
  source_gen: ^1.2.3
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  source_gen_test: ^1.0.4
