// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbo432axUkrU7v4eHucMpUgVw_laPO_EE',
    appId: '1:719672419136:web:257f9beb2a864a55be50a5',
    messagingSenderId: '719672419136',
    projectId: 'pub-dev-client',
    authDomain: 'pub-dev-client.firebaseapp.com',
    storageBucket: 'pub-dev-client.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5U1GJrEV13ewOHS2eF_hisKTHa30STnc',
    appId: '1:719672419136:android:999af3579395fd9dbe50a5',
    messagingSenderId: '719672419136',
    projectId: 'pub-dev-client',
    storageBucket: 'pub-dev-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCClNcn1Z114mbDvZt_7kKnT3lA4K2Zyac',
    appId: '1:719672419136:ios:e6e7675ad63019babe50a5',
    messagingSenderId: '719672419136',
    projectId: 'pub-dev-client',
    storageBucket: 'pub-dev-client.appspot.com',
    iosClientId: '719672419136-fa7n9o21vb1fhem21gfqh3r0u4ng244a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCClNcn1Z114mbDvZt_7kKnT3lA4K2Zyac',
    appId: '1:719672419136:ios:e6e7675ad63019babe50a5',
    messagingSenderId: '719672419136',
    projectId: 'pub-dev-client',
    storageBucket: 'pub-dev-client.appspot.com',
    iosClientId: '719672419136-fa7n9o21vb1fhem21gfqh3r0u4ng244a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pub',
  );
}
