name: my_project

packages:
  - website
  - packages/**
  - examples/**
  - tools/**

scripts:
  # we voluntarily do not use melos inside goldens
  postbootstrap: |
    cd MELOS_ROOT_PATH/packages/riverpod_cli/fixtures/notifiers/input && 
    flutter pub get && 
    cd MELOS_ROOT_PATH/packages/riverpod_cli/fixtures/notifiers/golden && 
    flutter pub get &&
    cd MELOS_ROOT_PATH/packages/riverpod_cli/fixtures/unified_syntax/input && 
    flutter pub get &&
    cd MELOS_ROOT_PATH/packages/riverpod_cli/fixtures/unified_syntax/golden && 
    flutter pub get

  generate:
    run: melos exec --depends-on=lint_visitor_generator -- "dart run build_runner build -d" && melos exec --depends-on=build_runner --no-depends-on=lint_visitor_generator -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.
