name: workspace
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  custom_lint:
  internal_lint:
    path: packages/internal_lint
  riverpod_lint:

workspace:
  - benchmarks
  - examples/counter
  - examples/marvel
  - examples/pub
  - examples/random_number
  - examples/stackoverflow
  - examples/todos
  - packages/flutter_riverpod/example
  - packages/flutter_riverpod
  - packages/hooks_riverpod/example
  - packages/hooks_riverpod
  - packages/lint_visitor_generator
  - packages/internal_lint
  - packages/riverpod/example
  - packages/riverpod
  - packages/riverpod_analyzer_utils
  - packages/riverpod_analyzer_utils_tests
  - packages/riverpod_annotation
  - packages/riverpod_generator/integration/build_yaml
  - packages/riverpod_generator
  - packages/riverpod_lint
  # Custom_lint doesn't handle plugins from workspaces yet
  # - packages/riverpod_lint_flutter_test
  - packages/riverpod_sqflite/example
  - packages/riverpod_sqflite
  - tools/generate_providers
  - website

dependency_overrides:
  build:
    git:
      url: https://github.com/dart-lang/build
      path: build
      ref: 8355dd011de981e60ad0c333ea7c10beb024b07e
  build_resolvers:
    git:
      url: https://github.com/dart-lang/build
      path: build_resolvers
      ref: 8355dd011de981e60ad0c333ea7c10beb024b07e
  build_runner:
    git:
      url: https://github.com/dart-lang/build
      path: build_runner
      ref: 8355dd011de981e60ad0c333ea7c10beb024b07e
  build_runner_core:
    git:
      url: https://github.com/dart-lang/build
      path: build_runner_core
      ref: 8355dd011de981e60ad0c333ea7c10beb024b07e
  meta: ^1.16.0
  source_gen: ^3.0.0