name: workspace
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  custom_lint:
  internal_lint:
    path: packages/internal_lint
  riverpod_lint:

workspace:
  - benchmarks
  - examples/first_app
  - examples/counter
  - examples/marvel
  - examples/pub
  - examples/random_number
  - examples/stackoverflow
  - examples/todos
  - packages/flutter_riverpod/example
  - packages/flutter_riverpod
  - packages/hooks_riverpod/example
  - packages/hooks_riverpod
  - packages/lint_visitor_generator
  - packages/internal_lint
  - packages/riverpod/example
  - packages/riverpod
  - packages/riverpod_analyzer_utils
  - packages/riverpod_analyzer_utils_tests
  - packages/riverpod_annotation
  - packages/riverpod_generator/integration/build_yaml
  - packages/riverpod_generator
  - packages/riverpod_lint
  # Custom_lint doesn't handle plugins from workspaces yet
  # - packages/riverpod_lint_flutter_test
  - packages/riverpod_sqflite/example
  - packages/riverpod_sqflite
  - tools/generate_providers
  - website
dependencies:
  flutter_riverpod: ^3.0.0-dev.18
