name: workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - benchmarks
  - examples/counter
  - examples/marvel
  - examples/pub
  - examples/random_number
  - examples/stackoverflow
  - examples/todos
  - packages/flutter_riverpod/example
  - packages/flutter_riverpod
  - packages/hooks_riverpod/example
  - packages/hooks_riverpod
  - packages/lint_visitor_generator
  - packages/riverpod/example
  - packages/riverpod
  - packages/riverpod_analyzer_utils
  - packages/riverpod_analyzer_utils_tests
  - packages/riverpod_annotation
  - packages/riverpod_generator/integration/build_yaml
  - packages/riverpod_generator
  - packages/riverpod_graph
  - packages/riverpod_graph/test/integration/addition/golden
  - packages/riverpod_graph/test/integration/consumer_widget/golden
  - packages/riverpod_graph/test/integration/generated/golden
  - packages/riverpod_lint
  - packages/riverpod_lint_flutter_test
  - packages/riverpod_sqflite/example
  - packages/riverpod_sqflite
  - tools/generate_providers
  - website
