export const documentTitles = {
  'en': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "From `StateNotifier`",
    "migration/from_change_notifier": "From `ChangeNotifier`",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "introduction/why_riverpod": "Why Riverpod?",
    "introduction/getting_started": "Getting started",
    "from_provider/quickstart": "Quickstart",
    "from_provider/provider_vs_riverpod": "Provider vs Riverpod",
    "from_provider/motivation/motivation": "Motivation",
    "essentials/websockets_sync": "Websockets and synchronous execution",
    "essentials/testing": "Testing your providers",
    "essentials/side_effects": "Performing side effects",
    "essentials/provider_observer": "Logging and error reporting",
    "essentials/passing_args": "Passing arguments to your requests",
    "essentials/first_request": "Make your first provider/network request",
    "essentials/faq": "FAQ",
    "essentials/eager_initialization": "Eager initialization of providers",
    "essentials/do_dont": "DO/DON'T",
    "essentials/combining_requests": "Combining requests",
    "essentials/auto_dispose": "Clearing cache and reacting to state disposal",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "About hooks",
    "concepts/about_code_generation": "About code generation",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "Pull to refresh",
    "case_studies/cancel": "Debouncing/Cancelling network requests",
    "advanced/select": "Optimizing performance",
  },
  'zh-Hans': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "从 `StateNotifier` 迁移",
    "migration/from_change_notifier": "从 `ChangeNotifier` 迁移",
    "migration/0.14.0_to_1.0.0": "^0.14.0 到 ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 到 ^0.14.0",
    "introduction/why_riverpod": "为什么选择 Riverpod？",
    "introduction/getting_started": "入门指南",
    "from_provider/quickstart": "快速开始",
    "from_provider/provider_vs_riverpod": "Provider 对比 Riverpod",
    "from_provider/motivation/motivation": "动机",
    "essentials/websockets_sync": "Websocket 和同步执行",
    "essentials/testing": "测试你的提供者程序",
    "essentials/side_effects": "执行副作用",
    "essentials/provider_observer": "日志和错误报告",
    "essentials/passing_args": "将参数传递给您的请求",
    "essentials/first_request": "开始你的第一次 provider/network 请求",
    "essentials/faq": "FAQ 常见问题",
    "essentials/eager_initialization": "急切的初始化提供者程序",
    "essentials/do_dont": "最佳实践",
    "essentials/combining_requests": "组合请求",
    "essentials/auto_dispose": "清除缓存并对状态处置做出反应",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "关于 Hooks（钩子）",
    "concepts/about_code_generation": "关于代码生成",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "下拉刷新",
    "case_studies/cancel": "网络请求的去抖动或取消",
    "advanced/select": "性能优化",
  },
  'ru': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "С ^0.14.0 на ^1.0.0",
    "migration/0.13.0_to_0.14.0": "С ^0.13.0 на ^0.14.0",
    "cookbooks/testing": "Тестирование",
    "cookbooks/search_as_we_type": "Поиск во мере ввода",
    "concepts/reading": "Чтение провайдера",
    "concepts/providers": "Провайдеры",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/combining_providers": "Объединение состояний провайдеров",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Введение",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'ko': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "`StateNotifier`에서",
    "migration/from_change_notifier": "`ChangeNotifier`에서",
    "migration/0.14.0_to_1.0.0": "^0.14.0에서 ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0에서 ^0.14.0",
    "introduction/why_riverpod": "왜 Riverpod인가?",
    "introduction/getting_started": "시작하기",
    "from_provider/quickstart": "빠른 시작",
    "from_provider/provider_vs_riverpod": "Provider vs Riverpod",
    "from_provider/motivation/motivation": "동기부여(Motivation)",
    "essentials/websockets_sync": "웹소켓 및 동기 실행",
    "essentials/testing": "providers 테스트하기",
    "essentials/side_effects": "부가 작업 수행(Performing side effects)",
    "essentials/provider_observer": "로깅 및 오류 보고",
    "essentials/passing_args": "요청에 인자 전달하기",
    "essentials/first_request": "첫 번째 provider/네트워크 요청 만들기",
    "essentials/faq": "자주 묻는 질문(FAQ)",
    "essentials/eager_initialization": "Providers의 빠른 초기화(Eager initialization)",
    "essentials/do_dont": "권장사항(DO/DON'T)",
    "essentials/combining_requests": "요청 결합하기",
    "essentials/auto_dispose": "캐시 지우기 및 상태 폐기(disposal)에 반응하기",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "훅(hooks)에 대한 정보",
    "concepts/about_code_generation": "코드 생성(Code generation)에 대한 정보",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "당겨서 새로고침(Pull to refresh)",
    "case_studies/cancel": "네트워크요청 디바운싱/취소 (Debouncing/Cancelling)",
    "advanced/select": "성능 최적화하기",
  },
  'ja': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 → ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 → ^0.14.0",
    "cookbooks/testing": "テスト",
    "concepts/reading": "プロバイダの利用方法",
    "concepts/providers": "プロバイダとは",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/combining_providers": "プロバイダのステートを組み合わせる",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "はじめに",
    "introduction": "イントロダクション",
    "about_code_generation": "コードジェネレーション",
  },
  'it': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "Da `StateNotifier`",
    "migration/from_change_notifier": "Da `ChangeNotifier`",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "introduction/why_riverpod": "Perché Riverpod?",
    "introduction/getting_started": "Introduzione",
    "from_provider/quickstart": "Quickstart",
    "from_provider/provider_vs_riverpod": "Provider vs Riverpod",
    "from_provider/motivation/motivation": "Motivazione",
    "essentials/websockets_sync": "Websocket ed esecuzione sincrona",
    "essentials/testing": "Testare i tuoi provider",
    "essentials/side_effects": "Eseguire side effects",
    "essentials/provider_observer": "Logging e segnalazione degli errori",
    "essentials/passing_args": "Passare parametri alle tue richieste",
    "essentials/first_request": "Effettua la tua prima richiesta di provider/rete",
    "essentials/faq": "FAQ",
    "essentials/eager_initialization": "Inizializzazione anticipata dei provider",
    "essentials/do_dont": "FARE/NON FARE",
    "essentials/combining_requests": "Combinare richieste",
    "essentials/auto_dispose": "Svuotare la cache e reagire alla cancellazione dello stato",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "Informazioni sugli hook",
    "concepts/about_code_generation": "Informazioni sulla generazione del codice",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "Pull to refresh (trascina per aggiornare)",
    "case_studies/cancel": "Respingere (Debouncing)/Cancellare richieste di rete",
    "advanced/select": "Ottimizzare le performance",
  },
  'fr': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 vers ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 vers ^0.14.0",
    "cookbooks/testing": "Tests",
    "cookbooks/search_as_we_type": undefined,
    "concepts/why_immutability": "Pourquoi l'Immuabilité",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Lire un Provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Cycles de vie des Provider",
    "concepts/combining_providers": "Combiner des providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Débuter",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
    "introduction": "Introduction",
    "about_code_generation": "À propos de la génération de code",
    "riverpod_for_provider_users": "Riverpod pour les utilisateurs de Provider",
    "about_hooks": "À propos des hooks",
  },
  'es': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 a ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 a ^0.14.0",
    "cookbooks/testing": "Testing",
    "concepts/reading": "Leyendo un Provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/combining_providers": "Combinando providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Empezando",
  },
  'bn': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/testing": "টেস্টিং",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/reading": "প্রভাইডার রিড করা",
    "concepts/providers": "প্রভাইডাররা",
    "concepts/provider_observer": "প্রভাইডার অবসার্বার",
    "concepts/combining_providers": "প্রভাইডার যুক্ত করা",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Getting started",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'de': {
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/reading": "Reading a provider",
    "concepts/providers": "Providers",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/combining_providers": "Combining providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Getting started",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
};
export const outdatedTranslations = [
{"countryCode":"ru","id":"providers/future_provider","englishPath":"/docs/providers/future_provider"},
];
