export const documentTitles = {
  'en': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "From `StateNotifier`",
    "migration/from_change_notifier": "From `ChangeNotifier`",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "introduction/why_riverpod": "Why Riverpod?",
    "introduction/getting_started": "Getting started",
    "from_provider/quickstart": "Quickstart",
    "from_provider/provider_vs_riverpod": "Provider vs Riverpod",
    "from_provider/motivation/motivation": "Motivation",
    "essentials/websockets_sync": "Websockets and synchronous execution",
    "essentials/testing": "Testing your providers",
    "essentials/side_effects": "Performing side effects",
    "essentials/provider_observer": "Logging and error reporting",
    "essentials/passing_args": "Passing arguments to your requests",
    "essentials/first_request": "Make your first provider/network request",
    "essentials/faq": "FAQ",
    "essentials/eager_initialization": "Eager initialization of providers",
    "essentials/do_dont": "DO/DON'T",
    "essentials/combining_requests": "Combining requests",
    "essentials/auto_dispose": "Clearing cache and reacting to state disposal",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "About hooks",
    "concepts/about_code_generation": "About code generation",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "Pull to refresh",
    "case_studies/cancel": "Debouncing/Cancelling network requests",
    "advanced/select": "Optimizing performance",
  },
  'zh-Hans': {
    "riverpod_for_provider_users": "给Provider开发者的Riverpod指南",
    "introduction": "介绍",
    "getting_started": "开始上手",
    "about_hooks": "关于钩子",
    "about_code_generation": "关于代码生成",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "cookbooks/testing": "测试",
    "concepts/why_immutability": "为何需要不可变性",
    "concepts/scopes": "作用域",
    "concepts/reading": "读取 Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider生命周期",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "组合 Provider 状态",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
  },
  'ko': {
    "riverpod_for_provider_users": "Provider사용자를 위한 Riverpod 가이드",
    "introduction": "소개",
    "getting_started": "시작하기",
    "about_hooks": "hooks 알아보기",
    "about_code_generation": "Code Generation 알아보기",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "cookbooks/testing": "테스트",
    "concepts/why_immutability": "불변성(Immutability)의 중요성",
    "concepts/reading": "프로바이더 읽기",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "프로바이더란?",
    "concepts/combining_providers": "프로바이더 결합하기",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/search_as_we_type": "Search as we type",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'fr': {
    "riverpod_for_provider_users": "Riverpod pour les utilisateurs de Provider",
    "introduction": "Introduction",
    "getting_started": "Débuter",
    "about_hooks": "À propos des hooks",
    "about_code_generation": "À propos de la génération de code",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "cookbooks/testing": "Tests",
    "concepts/why_immutability": "Pourquoi l'Immuabilité",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Lire un Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Cycles de vie des Provider",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combiner des providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 vers ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 vers ^0.14.0",
    "cookbooks/search_as_we_type": undefined,
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'ja': {
    "introduction": "イントロダクション",
    "getting_started": "はじめに",
    "about_code_generation": "コードジェネレーション",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "cookbooks/testing": "テスト",
    "concepts/reading": "プロバイダの利用方法",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "プロバイダとは",
    "concepts/combining_providers": "プロバイダのステートを組み合わせる",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 → ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 → ^0.14.0",
  },
  'ru': {
    "getting_started": "Введение",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "cookbooks/testing": "Тестирование",
    "concepts/reading": "Чтение провайдера",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "Провайдеры",
    "concepts/combining_providers": "Объединение состояний провайдеров",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "С ^0.14.0 на ^1.0.0",
    "migration/0.13.0_to_0.14.0": "С ^0.13.0 на ^0.14.0",
    "cookbooks/search_as_we_type": "Поиск во мере ввода",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'es': {
    "getting_started": "Empezando",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "cookbooks/testing": "Testing",
    "concepts/reading": "Leyendo un Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combinando providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 a ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 a ^0.14.0",
  },
  'de': {
    "getting_started": "Getting started",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "cookbooks/testing": "Testing",
    "concepts/reading": "Reading a provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combining providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/search_as_we_type": "Search as we type",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'bn': {
    "getting_started": "Getting started",
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "cookbooks/testing": "টেস্টিং",
    "concepts/reading": "প্রভাইডার রিড করা",
    "concepts/provider_observer": "প্রভাইডার অবসার্বার",
    "concepts/providers": "প্রভাইডাররা",
    "concepts/combining_providers": "প্রভাইডার যুক্ত করা",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/search_as_we_type": "Search as we type",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'it': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "cookbooks/testing": "Testing",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/search_as_we_type": "Search as we type",
    "migration/from_state_notifier": "Da `StateNotifier`",
    "migration/from_change_notifier": "Da `ChangeNotifier`",
    "introduction/why_riverpod": "Perché Riverpod?",
    "introduction/getting_started": "Introduzione",
    "from_provider/quickstart": "Quickstart",
    "from_provider/provider_vs_riverpod": "Provider vs Riverpod",
    "from_provider/motivation/motivation": "Motivazione",
    "essentials/websockets_sync": "Websocket ed esecuzione sincrona",
    "essentials/testing": "Testare i tuoi provider",
    "essentials/side_effects": "Eseguire side effects",
    "essentials/provider_observer": "Logging e segnalazione degli errori",
    "essentials/passing_args": "Passare parametri alle tue richieste",
    "essentials/first_request": "Effettua la tua prima richiesta di provider/rete",
    "essentials/faq": "FAQ",
    "essentials/eager_initialization": "Inizializzazione anticipata dei provider",
    "essentials/do_dont": "FARE/NON FARE",
    "essentials/combining_requests": "Combinare richieste",
    "essentials/auto_dispose": "Svuotare la cache e reagire alla cancellazione dello stato",
    "concepts/about_hooks": "Informazioni sugli hook",
    "concepts/about_code_generation": "Informazioni sulla generazione del codice",
    "case_studies/pull_to_refresh": "Pull to refresh (trascina per aggiornare)",
    "case_studies/cancel": "Respingere (Debouncing)/Cancellare richieste di rete",
    "advanced/select": "Ottimizzare le performance",
  },
};
export const outdatedTranslations = [
{"countryCode":"ru","id":"providers/future_provider","englishPath":"/docs\\providers/future_provider"},
];
