export const documentTitles = {
  'en': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "From `StateNotifier`",
    "migration/from_change_notifier": "From `ChangeNotifier`",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "introduction/why_riverpod": "Why Riverpod?",
    "introduction/getting_started": "Getting started",
    "from_provider/quickstart": "Quickstart",
    "from_provider/provider_vs_riverpod": "Provider vs Riverpod",
    "from_provider/motivation/motivation": "Motivation",
    "essentials/websockets_sync": "Websockets and synchronous execution",
    "essentials/testing": "Testing your providers",
    "essentials/side_effects": "Performing side effects",
    "essentials/provider_observer": "Logging and error reporting",
    "essentials/passing_args": "Passing arguments to your requests",
    "essentials/first_request": "Make your first provider/network request",
    "essentials/faq": "FAQ",
    "essentials/eager_initialization": "Eager initialization of providers",
    "essentials/do_dont": "DO/DON'T",
    "essentials/combining_requests": "Combining requests",
    "essentials/auto_dispose": "Clearing cache and reacting to state disposal",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "About hooks",
    "concepts/about_code_generation": "About code generation",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "Pull to refresh",
    "case_studies/cancel": "Debouncing/Cancelling network requests",
    "advanced/select": "Optimizing performance",
  },
  'zh-Hans': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/from_state_notifier": "从 `StateNotifier` 迁移",
    "migration/from_change_notifier": "从 `ChangeNotifier` 迁移",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "introduction/why_riverpod": "为什么选择 Riverpod？",
    "introduction/getting_started": "入门指南",
    "from_provider/quickstart": "快速开始",
    "from_provider/provider_vs_riverpod": "Provider 对比 Riverpod",
    "from_provider/motivation/motivation": "动机",
    "essentials/websockets_sync": "Websocket 和同步执行",
    "essentials/testing": "测试你的提供者程序",
    "essentials/side_effects": "执行副作用",
    "essentials/provider_observer": "日志和错误报告",
    "essentials/passing_args": "将参数传递给您的请求",
    "essentials/first_request": "开始你的第一次 provider/network 请求",
    "essentials/faq": "FAQ 常见问题",
    "essentials/eager_initialization": "急切的初始化提供者程序",
    "essentials/do_dont": "最佳实践",
    "essentials/combining_requests": "组合请求",
    "essentials/auto_dispose": "清除缓存并对状态处置做出反应",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "Why Immutability",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Reading a Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Provider Lifecycles",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combining Provider States",
    "concepts/about_hooks": "关于 Hooks（钩子）",
    "concepts/about_code_generation": "关于代码生成",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "case_studies/pull_to_refresh": "下拉刷新",
    "case_studies/cancel": "网络请求的去抖动或取消",
    "advanced/select": "性能优化",
  },
  'ru': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "С ^0.14.0 на ^1.0.0",
    "migration/0.13.0_to_0.14.0": "С ^0.13.0 на ^0.14.0",
    "cookbooks/testing": "Тестирование",
    "cookbooks/search_as_we_type": "Поиск во мере ввода",
    "concepts/reading": "Чтение провайдера",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "Провайдеры",
    "concepts/combining_providers": "Объединение состояний провайдеров",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Введение",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'ko': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/testing": "테스트",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/why_immutability": "불변성(Immutability)의 중요성",
    "concepts/reading": "프로바이더 읽기",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "프로바이더란?",
    "concepts/combining_providers": "프로바이더 결합하기",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "시작하기",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
    "riverpod_for_provider_users": "Provider사용자를 위한 Riverpod 가이드",
    "introduction": "소개",
    "about_hooks": "hooks 알아보기",
    "about_code_generation": "Code Generation 알아보기",
  },
  'ja': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 → ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 → ^0.14.0",
    "cookbooks/testing": "テスト",
    "concepts/reading": "プロバイダの利用方法",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "プロバイダとは",
    "concepts/combining_providers": "プロバイダのステートを組み合わせる",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "はじめに",
    "introduction": "イントロダクション",
    "about_code_generation": "コードジェネレーション",
  },
  'it': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "da ^0.14.0 a ^1.0.0",
    "migration/0.13.0_to_0.14.0": "da ^0.13.0 a ^0.14.0",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/reading": "Leggere un provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "I Provider",
    "concepts/combining_providers": "Combinare stati di provider",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Introduzione",
  },
  'fr': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/notifier_provider": "(Async)NotifierProvider",
    "providers/future_provider": "FutureProvider",
    "providers/change_notifier_provider": "ChangeNotifierProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 vers ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 vers ^0.14.0",
    "cookbooks/testing": "Tests",
    "concepts/why_immutability": "Pourquoi l'Immuabilité",
    "concepts/scopes": "Scopes",
    "concepts/reading": "Lire un Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/provider_lifecycles": "Cycles de vie des Provider",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combiner des providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Débuter",
    "riverpod_for_provider_users": "Riverpod pour les utilisateurs de Provider",
    "introduction": "Introduction",
    "about_hooks": "À propos des hooks",
    "about_code_generation": "À propos de la génération de code",
  },
  'es': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 a ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 a ^0.14.0",
    "cookbooks/testing": "Testing",
    "concepts/reading": "Leyendo un Provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combinando providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Empezando",
  },
  'bn': {
    "providers/stream_provider": "StreamProvider",
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/testing": "টেস্টিং",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/reading": "প্রভাইডার রিড করা",
    "concepts/provider_observer": "প্রভাইডার অবসার্বার",
    "concepts/providers": "প্রভাইডাররা",
    "concepts/combining_providers": "প্রভাইডার যুক্ত করা",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Getting started",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
  'de': {
    "providers/state_provider": "StateProvider",
    "providers/state_notifier_provider": "StateNotifierProvider",
    "providers/provider": "Provider",
    "providers/future_provider": "FutureProvider",
    "migration/0.14.0_to_1.0.0": "^0.14.0 to ^1.0.0",
    "migration/0.13.0_to_0.14.0": "^0.13.0 to ^0.14.0",
    "cookbooks/testing": "Testing",
    "cookbooks/search_as_we_type": "Search as we type",
    "concepts/reading": "Reading a provider",
    "concepts/provider_observer": "ProviderObserver",
    "concepts/providers": "Providers",
    "concepts/combining_providers": "Combining providers",
    "concepts/modifiers/family": ".family",
    "concepts/modifiers/auto_dispose": ".autoDispose",
    "getting_started": "Getting started",
    "cookbooks/refresh": "Pull-to-refresh / Retry-on-error",
  },
};
export const outdatedTranslations = [
{"countryCode":"ru","id":"providers/future_provider","englishPath":"/docs\\providers/future_provider"},
];
