analyzer:
  exclude:
    # Files with errors on purpose
    - test/lints/notifier_extends/notifier_extends.g.dart
    - test/lints/functional_ref/functional_ref.g.dart
    - test/lints/functional_ref/fix/auto_import.g.dart
    - test/lints/functional_ref/fix/use_prefix.g.dart
  errors:
    # Remove once we require analyzer 8.0.0
    # We currently support both 7.0 and 8.0, so we can't migrate yet.
    deprecated_member_use: ignore

# analysis_options.yaml
formatter:
  # Preserving commas for the sake of testing code with/without commas
  trailing_commas: preserve

plugins:
  riverpod_lint:
    path: /Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod_lint