targets:
  $default:
    builders:
      riverpod_generator:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*

builders:
  riverpod_generator:
    import: "package:riverpod_generator/builder.dart"
    builder_factories: ["riverpodBuilder"]
    build_extensions: {".dart": [".riverpod.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]