name: cosmic_frontmatter
description: Parse frontmatter from a YAML file. Use this along-side a markdown plugin such as flutter_markdown.
version: 1.0.2
repository: https://github.com/cosmic-horse/cosmic_frontmatter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.5.0
