name: first_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  dio: 5.10.0
  flutter:
    sdk: flutter
  flutter_riverpod:

flutter:
  uses-material-design: true
