// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'all_test.dart' as all_test;
import 'auto_dispose_test.dart' as auto_dispose_test;
import 'builders_test.dart' as builders_test;
import 'common_test.dart' as common_test;
import 'container_observer_test.dart' as container_observer_test;
import 'family_test.dart' as family_test;
import 'framework2/framework_test.dart' as framework2_framework_test;
import 'framework2/provider_test.dart' as framework2_provider_test;
import 'framework2/scoped_provider_test.dart'
    as framework2_scoped_provider_test;
import 'framework2/select_test.dart' as framework2_select_test;
import 'framework2/state_provider_test.dart' as framework2_state_provider_test;
import 'framework2/stream_provider_test.dart'
    as framework2_stream_provider_test;
import 'framework_test.dart' as framework_test;
import 'provider/auto_dispose_state_notifier_provider_test.dart'
    as provider_auto_dispose_state_notifier_provider_test;
import 'provider/future_provider_test.dart' as provider_future_provider_test;
import 'provider/provider_test.dart' as provider_provider_test;
import 'provider/state_notifier_provider_test.dart'
    as provider_state_notifier_provider_test;
import 'provider/state_provider_test.dart' as provider_state_provider_test;
import 'provider/stream_provider_test.dart' as provider_stream_provider_test;
import 'ref_watch_test.dart' as ref_watch_test;
import 'uni_directional_test.dart' as uni_directional_test;
import 'visit_states_test.dart' as visit_states_test;

void main() {
  uni_directional_test.main();
  builders_test.main();
  visit_states_test.main();
  container_observer_test.main();
  framework2_select_test.main();
  framework2_provider_test.main();
  framework2_state_provider_test.main();
  framework2_stream_provider_test.main();
  framework2_framework_test.main();
  framework2_scoped_provider_test.main();
  provider_provider_test.main();
  provider_state_notifier_provider_test.main();
  provider_auto_dispose_state_notifier_provider_test.main();
  provider_state_provider_test.main();
  provider_stream_provider_test.main();
  provider_future_provider_test.main();
  common_test.main();
  ref_watch_test.main();
  family_test.main();
  all_test.main();
  auto_dispose_test.main();
  framework_test.main();
}
