name: riverpod_shared_preferences
description: An adapter to connect shared_preferences with Riverpod.
version: 0.1.0
environment:
  sdk: "^3.0.0"

dependencies:
  http: ^1.2.2
  riverpod: ^3.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  test: ^1.25.8
