import: ../../analysis_options.yaml
analyzer:
  # enable riverpod_lint
  plugins:
    - custom_lint
  errors:
    # Some assets are voluntarily gitignored
    asset_does_not_exist: ignore
    # I prefer specifying a parameter on a widget even if they are unused (such as Key)
    # for the sake of consistency.
    unused_element_parameter: false