include: ../analysis_options.yaml
analyzer:
  exclude:
    - build/**
    - i18n/**
  errors:
    todo: ignore
    # Needed to not update the documentation before a release is made
    deprecated_member_use: false

linter:
  rules:
    require_trailing_commas: false
