name: Check CHANGELOG.md

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v2.7.1
        with:
          channel: master

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Install "semantic_changelog"
        run: dart pub global activate -s git https://github.com/rrousselGit/semantic_changelog

      - run: git fetch origin master:refs/remotes/origin/master
      - run: semantic_changelog check origin/master