name: Cleanup Workflow

on:
  workflow_run:
    workflows:
      - "build"
      - "changelog"
      - check_generation
      - riverpod_lint
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        run: echo "This is the cleanup job."
