name: Check website/src/outdated_translations.json

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - run: flutter pub get
        name: Installing website dependencies
        working-directory: website

      - run: ls
        working-directory: website
      - run: pwd
        working-directory: website

      - name: Running the outdated translation generator
        run: dart ./src/outdated_docs_generator.dart
        working-directory: website

      - name: Updating the list of outdated translations, if any
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update outdated translations (generated by GitHub actions)"
          git push
        working-directory: website
